version: '3.9'

services:
  web-scraping:
    container_name: web-scraping
    volumes:
      - .:/web-scraping
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
     - web-scraping

volumes:
  static: