version: '3.9'

services:
  web-scraping:
    volumes:
      - .:/web-scraping
      - static:/web-scraping/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/web-scraping/static
    ports:
      - "80:80"
    depends_on:
     - web-scraping

volumes:
  static: