# Generated by Django 4.1.5 on 2023-02-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
    ]
